version: '3'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./reactdemo.crt:/etc/ssl/certs/reactdemo.crt
      - ./reactdemo.key:/etc/ssl/private/reactdemo.key
    depends_on:
      - nextjs
